routes:
  /: 
    template: home
    data: page.home
  /signup/: members-signup # Free sign up page
  /signin/: members-signin # Member sign in
  /account/: members-account # Member sign i
  
collections:
  /:
    permalink: /{slug}/
    filter: tag:-[podcast,book]
  /nooks/:
    permalink: /nooks/{slug}/
    template: nooks
    filter: primary_tag:nooks


taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/